### ISSUE TITLE
flex overflow make some bug

### ISSUE THREAD

**Issue by cpm828** [1340641314/flex.css#10]
when I use the flex.css,the `over:flow:hidden` always make some bug, In some android phone, If the `<p><p>` use the flex.css,they alaways was cliped by the flex.css.I hope you can modify the bug. thanks

在使用你的flex.css时，overflow:hidden 经常会造成一些bug，会将div的超出部分裁掉，在一些烂安卓手机上，当给p段落使用时，也会造成段落上面被裁掉的现象，应该也是overflow引起，我可以直接将overflow:hidden注释掉么，这样会不会造成什么问题。希望能抽空改进一些，谢谢！

**Comment by lzxb** [comment]
很多人都反应过这个问题，其实加上overflow:hidden主要是防止使用行内标签和一些地段机器中出现盒子无法撑开的bug。

**Comment by lzxb** [comment]
已经发了一个新的版本(1.1.7)，去掉了overflow:hidden
如果出现这种bug，以后只能让别人自己手动增加overflow:hidden了
如果是npm安装的，升级包版本即可
