### ISSUE TITLE
flex-box="1" 这个样式里面为何没有 flex-basis ？

### ISSUE THREAD

**Issue by zivgit** [1340641314/flex.css#11]
既然`flex-box="1"`是设置`flex`，那为什么没有定义`flex-basis`。
因为这个，我给三个元素的头尾两个元素设置`flex-box="1"`，希望他们有一样的size，结果因为第一个元素内部有文字内容，所以比最后的元素大。

**Comment by lzxb** [comment]
他是剩余空间的分配，也就是说去除掉文字的宽度来进行分配的
