### ISSUE TITLE
flex=:"box:first" 如果第一个子元素是img的时候，img设置的宽度会被width：auto覆盖

### ISSUE THREAD

**Issue by 2016geek** [1340641314/flex.css#15]
![image](https://user-images.githubusercontent.com/20659607/34429234-541448ca-ec90-11e7-9f7c-c93d0d4c5e75.png)

**Comment by lzxb** [comment]
像这种，建议再嵌套一层div。

**Comment by 2016geek** [comment]
项目里一直用这个，做的挺好的，真心感谢！

**Comment by lzxb** [comment]
3q，多谢支持
