### ISSUE TITLE
website is broken

### ISSUE THREAD

**Issue by xbigcat** [1340641314/flex.css#23]
lzxb.name/flex.css/

**Comment by xbigcat** [comment]
@lzxb

**Comment by lzxb** [comment]
抱歉，今天才看到，原因是域名过期了。。。。没有续费。。。

**Comment by rainbowzx** [comment]
@lzxb lzxb.name/flex.css/   网址进不去，有新替代的网址吗

**Comment by lzxb** [comment]
下午我去掉这个域名的绑定吧。

**Comment by lzxb** [comment]
http://lzxb.name/flex.css/
重新再试试，看看是否正常

**Comment by xbigcat** [comment]
@lzxb 还是不行

**Comment by lzxb** [comment]
清除一下chrome的DNS缓存试试

**Comment by xbigcat** [comment]
@lzxb 不行，在家在公司都不行

> 无法访问此网站 找不到 lzxb.name 的服务器 IP 地址。

**Comment by lzxb** [comment]
晚上我回去，找个其它手机试试。我这边测试都是可以了

**Comment by rainbowzx** [comment]
进不去的可以在codepen看到https://codepen.io/webstermobile/pen/apXEER/

**Comment by bibiuc** [comment]
> 进不去的可以在codepen看到https://codepen.io/webstermobile/pen/apXEER/

自己弄了。有代码就好
https://flexcss.kiduc.com/
