### ISSUE TITLE
demo无法查看了，请问是不维护了么

### ISSUE THREAD

**Issue by struggle-fish** [1340641314/flex.css#26]

**Comment by lzxb** [comment]
你是说这个地址吗？
我这边可以访问：http://lzxb.name/flex.css/

**Comment by struggle-fish** [comment]
> 你是说这个地址吗？
> 我这边可以访问：http://lzxb.name/flex.css/


那可能是我网的问题，我打开后是这样的
![image](https://user-images.githubusercontent.com/12171471/75332740-db54ff80-58bf-11ea-919d-243b8c3174b0.png)

**Comment by lzxb** [comment]
看起来像是DNS服务没有配置好。
