### ISSUE TITLE
on olde version webkit  dir:top  flex-box  first children node disappear。

### ISSUE THREAD

**Issue by YeChuan-Xing** [1340641314/flex.css#27]
dir:top 下 flex-box 中第一个节点，在旧版本 webkit 浏览器中会显示不出来，（英语太差了，还是汉语吧(lll￢ω￢)）
加上
[flex~="dir:top"] > [flex-box] > * {
  position: absolute;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
}
就可以了，测试机型 万恶的opp vivo

**Comment by lzxb** [comment]
你这样需要定制对应元素的样式，需要你自己处理。
