### ISSUE TITLE
Demo都下载不了了

### ISSUE THREAD

**Issue by chenyuqing20** [1340641314/flex.css#28]
Demo都下载不了了，可以更新一下吗？

**Comment by lzxb** [comment]
我周末抽时间处理一下。这个域名解析不生效

**Comment by bibiuc** [comment]
我自己部了一个 https://flexcss.kiduc.com

**Comment by lzxb** [comment]
> 我自己部了一个 https://flexcss.kiduc.com

可以来个PR吗？可以更换掉。

**Comment by bibiuc** [comment]
要改解析吗？我加上了。还是原来的地址http://lzxb.name/flex.css 或者 http://lzxb.github.io/flex.css

**Comment by bibiuc** [comment]
> Demo都下载不了了，可以更新一下吗？

就一个index.html

**Comment by lzxb** [comment]
> 要改解析吗？我加上了。还是原来的地址http://lzxb.name/flex.css 或者 http://lzxb.github.io/flex.css

直接修改成你的链接。
