### ISSUE TITLE
这个项目意义在哪里？？

### ISSUE THREAD

**Issue by zerofront** [1340641314/flex.css#3]
仅仅只是把该写在css里面的flex,写在html 标签的属性里面吗？？？

**Comment by lzxb** [comment]
@zerofront 对flex布局初学者来说，各种兼容性入坑少不了，进阶的话，可以使用autoprefixer来处理相关的兼容性问题，但是也会为了实现flex布局而新增很多class来实现对应的布局效果，当然了，也会有人把对应的布局属性封装成class来调用，但是很容易引起class过长的问题。从执行效率上，属性匹配的方式确实是比不上直接class匹配的效率高，但是从维护的角度看，我可以从短短的flex=“main:center cross:centere” 这个字来看出html的基本布局结构，之所以采用属性匹配的方式，也仅仅是因为可以写更少的代码

**Comment by CandySunPlus** [comment]
感觉 postcss+autoprefixer 是主流发展方向， 你这又是在 flexbox上适配出了一套体系。

**Comment by lzxb** [comment]
@CandySunPlus 本质上flex.css都是使用autoprefixer编译处理的，能够让你写html的时候，用最精简的代码，快速构建flex布局。

``` html
    <!-- 自己写flex布局 -->
    <style type="text/css">
        .box {
            display: flex
        }
    </style>
    <div class="box"></div>

    <!-- flex.css实现flex布局 -->
    <div flex></div>
```

**Comment by zerofront** [comment]
@lzxb 想了几天发现还是有点奇怪，违背了结构与样式分离的初衷。但是如果把这个整合成类的话，确实是类名很乱。还是觉得直接写好一些。请问autoprefixer 可以设置兼容uc吗？？我作了一个demo，是按列排布的，设置了flex-flow: wrap column 后其他浏览器都可以，而在UC下无法实现父元素高度不够的时候换列。

**Comment by lzxb** [comment]
@zerofront  这个是无解的，因为-webkit-box不支持。其实这个并矛盾，只是将布局从css中迁移到html中，css中少了布局的代码，然而其他的还是使用css来控制元素的显示风格

**Comment by zerofront** [comment]
如果不能用flex-wrap的话如何解决垂直排列，但是又要在第一列装不下的时候自动换行到下一列呢？

**Comment by lzxb** [comment]
@zerofront 这个目前暂时没有解决方法，需要换行的，我目前也是使用浮动布局

**Comment by zerofront** [comment]
@lzxb  请问 浮动如何实现按列排布？？https://www.zhihu.com/question/50584424?from=profile_question_card

**Comment by lzxb** [comment]
@zerofront 浮动布局，还是自己自己补习一下基础吧

**Comment by zerofront** [comment]
@lzxb 大哥，不是浮动布局不会，是浮动布局根本不能按列竖直排列下来，只能横着排～～～～～～～～～～

**Comment by lzxb** [comment]
@zerofront 明白了，我试试

**Comment by lzxb** [comment]
@zerofront 估计只能使用定位布局，使用js来动态计算了。。。

**Comment by evolutionjay** [comment]
想法挺好的。但我选择 Autoprefixer 直接 Chrome 24 配置一下完事。

**Comment by lzxb** [comment]
@evolutionjay 还是要看各人喜好，想怎么写就怎么写
