### ISSUE TITLE
非常喜欢你们的flex布局！但想请教是否有这种布局方法。

### ISSUE THREAD

**Issue by ringcrl** [1340641314/flex.css#5]
感觉很幸运，第一次接触flex布局就遇到了你们，这种属性的写法，优雅程度完胜那些写在class里面的。

但是对于flex布局还有很多不太熟悉的地方，虽然已经被他那么优雅的对齐方式给惊艳了。

现在有个问题，如果我想实现这样的布局，
![qq20161130-0](https://cloud.githubusercontent.com/assets/16740021/20736316/b942b236-b6e0-11e6-8e30-4c4702460fce.png)

每张图片外我给他包裹了一个长宽一致的div，这样比较好看，这时候第四章图片就出现排放问题了，如果我想出现一个滚动条，可以往右滚一下看完全部图片，或者说第四张图片换一行展示，不知道在flex的情况下该如何新增样式呢？

**Comment by lzxb** [comment]
flex.css不支持子元素换行，原因是旧版本flex-wrap: wrap;不支持
