### ISSUE TITLE
直接引入dist中的flex.css, 不管用

### ISSUE THREAD

**Issue by jackPanyj** [1340641314/flex.css#6]
首先很感谢你们。我把dist目录中的flex.css拷贝到了我的本地。然后发现在安卓4.2上不管用。在5.1上是好的。请问这是什么原因。

**Comment by lzxb** [comment]
可以上具体代码看看么，我自己测试下。

**Comment by jackPanyj** [comment]
抱歉。。不止为何现在好了。可能是我某些地方写错了。另外。。还有一个问题。
为何会设置`overflow:hidden`;
`[flex],[flex]>*,[flex]>[flex]{overflow:hidden}`

之前有个我有个子元素绝对定位需要在父元素之上。结果因为父元素是这个设置就被剪切了。

**Comment by lzxb** [comment]
这个是为了避免在一些旧的浏览器内核引发的一些奇怪的bug，所以默认设置了overflow:hidden;
你可以根据自己的需要去进行调整
