### ISSUE TITLE
盒子内部定位元素需要超出盒子不能显示问题

### ISSUE THREAD

**Issue by shengzhong5566** [1340641314/flex.css#7]
由于flex设置了overflow:hidden,则应用场景为盒子内部的定位元素需要超出盒子就不能显示出来了。
建议用其他清除浮动方式撑起盒子适应内部内容。如：给父元素加伪元素：after，样式清楚浮动就行

**Comment by lzxb** [comment]
ok，有时间修改一下这个问题
